config/routes.rb
Rails.application.routes.draw do
  get 'element/index'
  root to: "welcome#index"
  resources :table, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/element_controller.rb
class ElementController < ApplicationController
  def index
  end
end

app/controllers/table_controller.rb
class TableController < ApplicationController
	# before_action :table, only: %i[index show ]
  def index
    file = File.read("db/data.json")
    @elements = JSON.parse(file)
  end

  # GET /tables/1 or /tables/1.json
  def show
	file = File.read("db/data.json")
    	@elements = JSON.parse(file)
  end

  # GET /tables/new
  def new
    @element = elements.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables or /tables.json
  def create
    @element = elements.new(table_params)

    respond_to do |format|
      if @element.save
        format.html { redirect_to @element, notice: "Table was successfully created." }
        format.json { render :show, status: :created, location: @element }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1 or /tables/1.json
  def update
    respond_to do |format|
      if @element.update(table_params)
        format.html { redirect_to @table, notice: "Table was successfully updated." }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1 or /tables/1.json
  def destroy
    @element.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: "Table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @element = elements.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_params
      params.fetch(:element, {})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/element_helper.rb
module ElementHelper
end

app/views/element/index.html.erb
<h1>Element#index</h1>
<p>Find me in app/views/element/index.html.erb</p>

app/views/layouts/application.html.erb
<style>
  @font-face {
    font-family: octicons-anchor;
    src: url(https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/font/octicons.woff) format('woff');
  }

  * {
      box-sizing: border-box;
  }
  .tittle-row > h1:nth-child(1) {
	text-align
  }
 

</style>
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>PeriodicTable</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <h1>Tabela Periódica</h1>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/table/show.html.erb
<style>
	@font-face {
		font-family: octicons-anchor;
		src: url(https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/font/octicons.woff) format('woff');
	}

	* {
		box-sizing: border-box;
	}
	body {
		display: grid;
		grid-template-rows: 100px auto;
		grid-template-columns: 20% auto 20%;
		margin: 0 0;

	}
	div.container:nth-child(1) {
		grid-row: 1;	
		grid-column: 1/-1;
		background: #333333;
		color: white;
	}
	.row > h1:nth-child(1) {
		text-align: center
	}
	div.container:nth-child(3) {
		padding-top: 15px;
		justify-self: center;
		grid-row: 2;
		grid-column: 2;
		min-width: 750px;
	}
	.elemnt > ul:nth-child(1) {
		height: 100%;
		width: auto;
		margin: 0 0;
		padding: 0 0;
	}
	
	div.container:nth-child(3) {
		display: grid;
		grid-template-columns: 1fr 2fr;
		grid-gap: 10px;
	}
	.elemnt > ul:nth-child(1) > li:nth-child(1) {
		list-style: none;
		display: grid;
		
		grid-template-columns: 1fr 1fr;
		background:#8ced8c;
		border: 5px solid;
		border-color: rgb(31, 199, 31);
		border-radius: 3px;
		height: 260px;
		width: 260px;
		padding: 5px;
	}
	.elemnt > ul:nth-child(1) > li:nth-child(1) > div:nth-child(1) {
		grid-columns: 1;
		text-decoration: none;
		list-style: none;	
		display: flex;
		flex-direction: column;
		justify-content: space-between;
		align-items: flex-start;
		font-size: large;
		color: black;
	}
	.elemnt > ul:nth-child(1) > li:nth-child(1) > div:nth-child(1) > p:nth-child(2) {
		font-size: xx-large;
		font-weight: bold;
	}
	.elemnt > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(2) {
		grid-columns: 2;
		display:flex;
		flex-direction: column;
		align-items: flex-end;
	}
	.elemnt > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(2) > li {
		list-style: none;	
	}
	.elemnt > ul:nth-child(1) > li:nth-child(1) > div:nth-child(1) > p {
		margin:0 0;
	}
	.table {
		border-radius: 3px;
		box-shadow:inset 0 0 2rem rgba(0,0,0,.30);
	}
	.table > ul:nth-child(1) {
		margin: 0 0;
		padding: 0 0;
	}
	.table > ul:nth-child(1) > li:nth-child(1) {
		list-style: none;
	}
	.table > ul:nth-child(1) > li:nth-child(1) > div {
		display: flex;
		flex-direction: row;
		justify-content: space-between;
		padding: 10px;
	}
	.table > ul:nth-child(1) > li:nth-child(1) > div > h4 {
		margin-right: 5px;
	}
	.table > ul:nth-child(1) > li:nth-child(1) > div:nth-child(15) > ul {
		width: 100%;
		list-style: none;
		padding-left: 0;
		display: flex;
		flex-direction: row;
		justify-content: space-between;
	}
</style>
<div class="container">
	<div class="elemnt">
		<ul>
			<% @elements["order"].each do |element| %>
				<% if @elements[element]["name"] == "Hydrogen" %>
					<li>  
						<div>
							<p>	
								<%= @elements[element]["number"] %>
							</p>
							<p>
								<%= @elements[element]["symbol"] %>
							</p>
							<p>
								<%= @elements[element]["name"] %>
							</p>
							<p>
								<%= @elements[element]["atomic_mass"] %>
							</p>
						</div>	
						<ul>
							<% @elements[element]["shells"].each do |e| %>
								
								<li>
									<%= e %>
								</li>

							<% end %>
						</ul>
					</li>
				<% end %>
			<% end %>

		</ul> 
	</div>
	<div class="table">
		<ul>
			<% @elements["order"].each do |element| %>
				<% if @elements[element]["name"] == "Hydrogen" %>
					
					<li>  
						<div>
							<h4>
								Ebulição:
							</h4>
							<h6>
								<%= @elements[element]["boil"] %> °C
							</h6>
						</div>
						<div>
							<h4>
								Categoria:
							</h4>
							<h6>
								<%= @elements[element]["category"] %> 
							</h6>
						</div>
						<div>
							<h4>
								Densidade: 
							</h4>
							<h6>
								<%= @elements[element]["density"] %> kg/m3
							</h6>
						</div>
						<div>
							<h4>
								Descobridor: 
							</h4>
							<h6>
								<%= @elements[element]["discovered_by"] %>
							</h6>
						</div>
						<div>
							<h4>
								Fusão: 
							</h4>
							<h6>
								<%= @elements[element]["melt"] %> °C
							</h6>
						</div>
						<div>
							<h4>
								Cadivacidade térmica molar: 
							</h4>
							<h6>
								<%= @elements[element]["molar_heat"] %> cal/°C
							</h6>
						</div>
						<div>
							<h4>
								Nomeado por: 
							</h4>
							<h6>
								<%= @elements[element]["named_by"] %>
							</h6>
						</div>
						<div>
							<h4>
								Periodo: 
							</h4>
							<h6>	
								<%= @elements[element]["period"] %>
							</h6>
						</div>
						<div>
							<h4>
								Fase: 
							</h4>
							<h6>
								<%= @elements[element]["phase"] %>
							</h6>
						</div>
						<div>
							<h4>
								Fonte: 
							</h4>
							<h6>
								<%= @elements[element]["source"] %>
							</h6>
						</div>

						<div>
							<h4>
								Configuração eletrônica:
							</h4>
							<h6>
								<%= @elements[element]["electron_configuration"] %>
							</h6>
						</div>
						<div>
							<h4>
								Semântica de configuração de elétrons:
							</h4>
							<h6>
								<%= @elements[element]["electron_configuration_semantic"] %>
							</h6>
						</div>
						<div>
							<h4>
								Afinidade eletrônica: 
							</h4>
							<h6>
								<%= @elements[element]["electron_affinity"] %> KJ/mol
							</h6>
						</div>
						<div>
							<h4>
							Eletronegatividade: 
							</h4>
							<h6>
								<%= @elements[element]["electronegativity_pauling"] %>
							</h6>
						</div>
						
						<div>
							<ul>
								<h4>
									Potencial de ionização:
								</h4>
								<h6>
									<% @elements[element]["ionization_energies"].each do |e| %>
								
										<li>
											<%= e %> kJ/mol
										</li>

									<% end %>
								</h6>
							</ul>
						</div>
					</li>
				<% end %>
			<% end %>

		</ul> 
	</div>
	<div>
		<%= link_to "Voltar", table_index_path %>
	</div>
</div>